project:
  type: website
  output-dir: docs

website:
  title: "Lauren Berry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: climbing.qmd
        text: climbing
      - href: projects.qmd
        text: projects

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full

editor: visual

