project:
  type: website
  output-dir: docs

website:
  title: "Lauren Berry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - climbing.qmd
      - projects.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full

editor: visual

