project:
  type: website
  output-dir: docs

website:
  title: "Lauren Berry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd # create new page
        text: CV # include title so no .html
      - href: climbing.qmd
        text: climbing
      - href: projects.qmd
        text: projects

format:
  html:
    theme: 
    - styles.scss # seperate page to edit themes
    - minty # keeping base bootswatch theme
    mainfont: Mulish
    toc: true 
    page-layout: full

editor: visual

